# SPDX-FileCopyrightText: 2023 Ferdinand Thiessen <rpm@fthiessen.de>
# SPDX-License-Identifier: CC0-1.0
#
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
